# the data generated by this script is not related in 
# any way to an existing aircraft.  Component names and
# fault wording are realistic so the ouput reads
# realistically, but are completely fake.

import random
from datetime import date, timedelta

from database import get_connection, init_schema

SEED = 60  # deterministic output (get it? "60".... UH-"60")

# most commonly -M. You will get Alphas in the random generation, but they won't be present in real-world
MODELS = ["UH-60A", "UH-60L", "UH-60M", "UH-60M", "HH-60M"]  

UNITS = [
    "A Co, 2-101 AVN", "B Co, 2-101 AVN", "C Co, 1-3 AVN",
    "A Co, 1-227 AVN", "B Co, 3-25 AVN", "C Co, 4-2 AVN",
    "Det 1, 1-169 AVN", "A Co, 2-4 AVN",
]

# (name, category, lifetime hours trend for the component)
COMPONENTS = [
    ("Main Transmission Module", "Drivetrain", 2500),
    ("Intermediate Gearbox (IGB)", "Drivetrain", 3000),
    ("Tail Gearbox (TGB)", "Drivetrain", 3000),
    ("Main Rotor Hub", "Rotor System", 5000),
    ("Main Rotor Blade", "Rotor System", 6000),
    ("Tail Rotor Hub", "Rotor System", 5000),
    ("Tail Rotor Blade", "Rotor System", 5500),
    ("No. 1 Engine (T700-GE-701D)", "Powerplant", 3000),
    ("No. 2 Engine (T700-GE-701D)", "Powerplant", 3000),
    ("Auxiliary Power Unit (APU)", "APU", 2000),
    ("No. 1 Hydraulic Pump Module", "Hydraulics", 2200),
    ("No. 2 Hydraulic Pump Module", "Hydraulics", 2200),
    ("Backup Hydraulic Pump", "Hydraulics", 2200),
    ("No. 1 AC Generator", "Electrical", 2500),
    ("No. 2 AC Generator", "Electrical", 2500),
    ("Stabilator Actuator", "Flight Controls", 4000),
    ("Pitch Change Link", "Flight Controls", 4500),
    ("Swashplate Assembly", "Flight Controls", 5000),
]

# fault description and realistic corrective action pairs, grouped by system
FAULTS = [
    ("MGB chip detector light illuminated in flight",
     "Replaced chip detector, MOC complete - good"),
    ("IGB oil level low on preflight",
     "Serviced IGB IAW TM, leak check good"),
    ("TGB oil leak observed at output seal",
     "Replaced output seal, ops/leak check good"),
    ("No. 1 ENG OIL PRESS caution displayed",
     "Replaced oil pressure transducer"),
    ("No. 2 engine torque split exceeds limits",
     "Performed engine topping check, adjusted HMU, within limits"),
    ("DECU fault code logged on No. 1 engine",
     "Cleared DECU fault, borescope serviceable, MOC good"),
    ("Excessive vibration in main rotor at 100% Nr",
     "Performed track and balance, vibration within limits"),
    ("Droop stop pounding noted on shutdown",
     "Inspected droop stops, replaced anti-flap assembly"),
    ("Pitch change link bearing play out of limits",
     "Replaced pitch change link, track and balance good"),
    ("Tail rotor pedal feedback / binding",
     "Lubricated controls, rigged tail rotor IAW TM"),
    ("No. 2 hydraulic pump low pressure caution",
     "Replaced No. 2 hydraulic pump module, leak check good"),
    ("BACKUP PUMP ON advisory remained illuminated",
     "Replaced backup pump pressure switch"),
    ("No. 1 generator dropped offline in flight",
     "Replaced No. 1 AC generator, electrical check good"),
    ("Stabilator failed to AUTO, manual slew required",
     "Adjusted stabilator rigging, replaced amplifier"),
    ("AFCS degraded — SAS 1 dropout",
     "Replaced SAS amplifier, AFCS check good"),
    ("APU failed to start, EGT exceedance",
     "R&R APU IAW TM, operational check good"),
    ("Main rotor blade tip cap delamination noted on inspection",
     "Replaced main rotor blade, track and balance good"),
    ("Fuel boost pump No. 2 inoperative",
     "Replaced fuel boost pump"),
    ("Hydraulic leak at No. 1 system B-nut fitting",
     "Tightened fittings, leak check good"),
    ("Engine inlet FOD screen partially obstructed",
     "Cleaned inlet screen, inspected compressor, serviceable"),
]

INSPECTIONS = [
    # (type, interval_hours, interval_days)  — None if na
    ("Phase Maintenance Inspection", 360, None),
    ("APU Hot Section Inspection", 1000, None),
    ("Engine Borescope Inspection", 750, None),
    ("Preventive Maintenance Service (PMS)", None, 30),
    ("Semiannual Inspection", None, 182),
    ("Annual Inspection", None, 365),
]

TODAY = date(2026, 6, 22)


def army_serial(rng):
    """Plausible Army serial: FY-sequence, e.g. 92-26471 (synthetic)."""
    fy = rng.choice(list(range(82, 100)) + list(range(0, 21)))
    seq = rng.randint(20000, 29999)
    return f"{fy:02d}-{seq}"


def serial_number(rng, prefix):
    return f"{prefix}-{rng.randint(1000, 9999)}"


def random_date(rng, start_days_ago, end_days_ago=0):
    delta = rng.randint(end_days_ago, start_days_ago)
    return (TODAY - timedelta(days=delta)).isoformat()


def main(num_aircraft=80, num_discrepancies=10000):
    rng = random.Random(SEED)
    init_schema()
    conn = get_connection()
    cur = conn.cursor()

    #  components
    for name, category, _life in COMPONENTS:
        cur.execute(
            "INSERT INTO components (component_name, category) VALUES (?, ?)",
            (name, category),
        )
    cur.execute("SELECT component_id, component_name FROM components")
    comp_ids = [row["component_id"] for row in cur.fetchall()]
    life_by_index = {i + 1: COMPONENTS[i][2] for i in range(len(COMPONENTS))}

    # aircraft 
    used_serials = set()
    aircraft_rows = []
    for _ in range(num_aircraft):
        tail = army_serial(rng)
        while tail in used_serials:
            tail = army_serial(rng)
        used_serials.add(tail)
        airframe_hours = round(rng.uniform(1200, 8200), 1)
        avg_monthly = round(rng.uniform(18, 55), 1)
        status = rng.choices(["FMC", "PMC", "NMC"], weights=[62, 25, 13])[0]
        model = rng.choice(MODELS)
        unit = rng.choice(UNITS)
        aircraft_rows.append((tail, model, unit, airframe_hours, avg_monthly, status))

    cur.executemany(
        """INSERT INTO aircraft
           (tail_number, model, unit, airframe_hours, avg_monthly_hours, status)
           VALUES (?, ?, ?, ?, ?, ?)""",
        aircraft_rows,
    )
    cur.execute("SELECT aircraft_id, airframe_hours FROM aircraft")
    aircraft = [(r["aircraft_id"], r["airframe_hours"]) for r in cur.fetchall()]

    #  time/life-tracked components per aircraft 
    ac_rows = []
    for aircraft_id, af_hours in aircraft:
        # Track ~12 of the catalog components on each airframe.
        tracked = rng.sample(range(1, len(COMPONENTS) + 1), 12)
        for comp_index in tracked:
            life = life_by_index[comp_index]
            # hours since new is some fraction of the component's life
            hsn = round(rng.uniform(0.15, 0.99) * life, 1)
            install = random_date(rng, start_days_ago=2000, end_days_ago=60)
            prefix = COMPONENTS[comp_index - 1][1][:3].upper()
            ac_rows.append((aircraft_id, comp_index,
                            serial_number(rng, prefix), hsn, life, install))
    cur.executemany(
        """INSERT INTO aircraft_components
           (aircraft_id, component_id, serial_number,
            hours_since_new, life_limit_hours, install_date)
           VALUES (?, ?, ?, ?, ?, ?)""",
        ac_rows,
    )

    # scheduled inspections
    insp_rows = []
    for aircraft_id, af_hours in aircraft:
        for itype, ihours, idays in INSPECTIONS:
            hours_at_last = None
            date_last = None
            if ihours is not None:
                # last done somewhere within this interval
                hours_at_last = round(af_hours - rng.uniform(0, ihours), 1)
                if hours_at_last < 0:
                    hours_at_last = 0.0
            if idays is not None:
                date_last = random_date(rng, start_days_ago=idays, end_days_ago=0)
            insp_rows.append((aircraft_id, itype, ihours, hours_at_last,
                              idays, date_last))
    cur.executemany(
        """INSERT INTO inspections
           (aircraft_id, inspection_type, interval_hours,
            hours_at_last, interval_days, date_last)
           VALUES (?, ?, ?, ?, ?, ?)""",
        insp_rows,
    )

    # discrepancy / fault history
    disc_rows = []
    aircraft_ids = [a[0] for a in aircraft]
    for _ in range(num_discrepancies):
        aircraft_id = rng.choice(aircraft_ids)
        component_id = rng.choice(comp_ids)
        fault, action = rng.choice(FAULTS)
        d = random_date(rng, start_days_ago=1825, end_days_ago=0)  # last ~5 yrs
        downtime = round(rng.choice(
            [0.5, 1, 2, 4, 6, 8, 12, 24, 48, 72]) * rng.uniform(0.5, 1.5), 1)
        status = rng.choices(["Closed", "Open"], weights=[88, 12])[0]
        disc_rows.append((aircraft_id, component_id, d, fault, action,
                          downtime, status))
    cur.executemany(
        """INSERT INTO discrepancies
           (aircraft_id, component_id, date, discrepancy_text,
            corrective_action, downtime_hours, status)
           VALUES (?, ?, ?, ?, ?, ?, ?)""",
        disc_rows,
    )

    conn.commit()

    # summary
    counts = {
        "aircraft": num_aircraft,
        "components": len(COMPONENTS),
        "tracked components": len(ac_rows),
        "inspections": len(insp_rows),
        "discrepancies": num_discrepancies,
    }
    conn.close()
    print("Synthetic UH-60 dataset generated:")
    for k, v in counts.items():
        print(f"  {v:>6,}  {k}")


if __name__ == "__main__":
    main()
